# Generated by Django 5.2.11 on 2026-02-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mob',
            field=models.CharField(max_length=10),
        ),
    ]
